// app/layout.tsx
import type { Metadata } from "next";
import "./globals.css";
import Providers from "./Providers/Provider"; 

export const metadata: Metadata = {
  title: "Joy-Meet",
  description: "Generated by web-componentsbd(Mehedi Hasan)",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        {/* ⭐️ Wrap children with client-side Providers */}
        <Providers>
          {children}
        </Providers>
      </body>
    </html>
  );
}